# Generated by Django 5.1.8 on 2025-05-04 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_certificates', '0002_alter_certificate_automated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateauthority',
            name='cert_profile_ev_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificateauthority',
            name='cert_profile_ov_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificateauthority',
            name='org_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
