# Generated by Django 5.2.3 on 2025-08-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_certificates', '0003_certificateauthority_cert_profile_ev_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='term',
            field=models.CharField(default='365', max_length=32),
        ),
    ]
