# Generated by Django 5.2.3 on 2025-09-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_certificates', '0004_alter_certificate_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='term',
            field=models.IntegerField(default=365),
        ),
    ]
