# Generated by Django 5.2.3 on 2025-09-08 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_certificates', '0005_alter_certificate_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='active',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_cert', to='netbox_certificates.certificateinstance'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='latest',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='latest_cert', to='netbox_certificates.certificateinstance'),
        ),
    ]
