# Generated by Django 5.2.3 on 2025-09-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_certificates', '0006_certificate_active_certificate_latest'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='monitor',
            field=models.BooleanField(default=True),
        ),
    ]
