# Generated by Django 5.2.3 on 2025-09-15 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_certificates', '0007_certificate_monitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='active',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_cert', to='netbox_certificates.certificateinstance'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='latest',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='latest_cert', to='netbox_certificates.certificateinstance'),
        ),
    ]
