# Generated by Django 5.2.6 on 2025-10-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_certificates', '0008_alter_certificate_active_alter_certificate_latest'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateinstance',
            name='monitor',
            field=models.BooleanField(default=False),
        ),
    ]
