# Generated by Django 5.2.6 on 2025-10-24 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_certificates', '0009_certificateinstance_monitor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificateinstance',
            old_name='monitor',
            new_name='surpassed',
        ),
    ]
