# Generated by Django 5.2.6 on 2025-10-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_certificates', '0010_rename_monitor_certificateinstance_surpassed'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='host_consistent',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
