# Generated by Django 5.2.6 on 2025-10-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_certificates', '0011_certificate_host_consistent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='host_consistent',
            field=models.BooleanField(null=True),
        ),
    ]
