# Generated by Django 5.2.7 on 2025-11-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_certificates', '0012_alter_certificate_host_consistent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='host_consistent',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
