# Generated by Django 5.2.7 on 2025-11-14 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_certificates', '0013_alter_certificate_host_consistent'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateauthority',
            name='cert_profile_wildcard_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
