# Generated by Django 5.2.10 on 2026-09-13 20:00

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0134_owner'),
        ('ipam', '0086_gfk_indexes'),
        ('netbox_certificates', '0014_certificateauthority_cert_profile_wildcard_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='term',
            field=models.IntegerField(default=199),
        ),
        migrations.CreateModel(
            name='CertificateAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('port', models.PositiveIntegerField(default=443)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('installed_serial', models.CharField(blank=True, max_length=100)),
                ('last_verified', models.DateTimeField(blank=True, null=True)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='netbox_certificates.certificate')),
                ('ip_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_assignments', to='ipam.ipaddress')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ('ip_address', 'port'),
                'unique_together': {('certificate', 'ip_address', 'port')},
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
