# Generated by Django 5.2.10 on 2026-09-14 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0086_gfk_indexes'),
        ('netbox_certificates', '0015_alter_certificate_term_certificateassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateassignment',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate_assignments', to='ipam.service'),
        ),
    ]
