# Generated by Django 5.2.10 on 2026-09-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_certificates', '0016_certificateassignment_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateassignment',
            name='installation_method',
            field=models.CharField(default='manual', max_length=50),
        ),
    ]
