# Generated by Django 5.2.10 on 2026-09-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_certificates', '0017_certificateassignment_installation_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateinstance',
            name='san',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
