# Generated by Django 5.2.10 on 2026-09-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_certificates', '0018_certificateinstance_san'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateinstance',
            name='type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
