# Generated by Django 5.2.10 on 2026-10-05 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_certificates', '0019_certificateinstance_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='device',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='vm',
        ),
        migrations.AddField(
            model_name='certificateassignment',
            name='installation_application',
            field=models.CharField(default='manual', max_length=50),
        ),
        migrations.AddField(
            model_name='certificateassignment',
            name='installation_type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
