# Generated by Django 5.2.10 on 2026-10-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_certificates', '0020_remove_certificate_device_remove_certificate_vm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='content',
        ),
        migrations.AlterField(
            model_name='certificate',
            name='fs_cert_location',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='fs_key_location',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
